# Generated by Django 4.1.7 on 2023-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_amount', models.FloatField()),
                ('price_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('image', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
