# Generated by Django 4.1.7 on 2023-02-22 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_fulldescription_offer_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='fullDescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
